import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Juvenyl
 */
public class Main extends javax.swing.JFrame {

        public static Connection myConn = null;
        public static PreparedStatement myPStmt = null;

       
        
        public Main() {
            initComponents();
        }   
               
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        Ok = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        EmpLabel = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        in = new javax.swing.JTextField();
        out = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TitleLabel.setText("Employee Record");

        Ok.setText("Ok");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        EmpLabel.setText("Employee ");

        e.setForeground(new java.awt.Color(204, 204, 204));

        in.setForeground(new java.awt.Color(204, 204, 204));
        in.setText("CheckIn");
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });

        out.setForeground(new java.awt.Color(204, 204, 204));
        out.setText("CheckOut");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(TitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmpLabel)
                            .addComponent(e)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(in, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TitleLabel)
                .addGap(18, 18, 18)
                .addComponent(EmpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ok)
                    .addComponent(Cancel))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        String data = e.getText(); 
        String data1 = in.getText(); 
        String data2 = out.getText(); 
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/landa", "root", "");
            System.out.println("Successful!");

            String check = "SELECT * FROM emp WHERE employee = ?";
            try (PreparedStatement check_ps = myCon.prepareStatement(check)) {
                check_ps.setString(1, data);
                try (ResultSet rs = check_ps.executeQuery()) {
                    if (rs.next()) { 
                        JOptionPane.showMessageDialog(null, "Employee already exists!", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);

                        
                        String duplicate = "INSERT INTO emp (employee, checkIN, checkOUT, invalid) VALUES (?, ?, ?, ?)";
                        try (PreparedStatement duplicate_ps = myCon.prepareStatement(duplicate)) {
                            duplicate_ps.setString(1, data);
                            duplicate_ps.setString(2, data1);
                            duplicate_ps.setString(3, data2);
                            duplicate_ps.setString(4, "Duplicate Entry"); 
                            duplicate_ps.executeUpdate();
                        }

                        return; 
                    }
                }
            }


            String sql = "INSERT INTO emp (employee, checkIN, checkOUT) VALUES (?,?,?)";
            try (PreparedStatement myPS = myCon.prepareStatement(sql)) {
                myPS.setString(1, data);
                myPS.setString(2, data1);
                myPS.setString(3, data2);
                int rowsAffected = myPS.executeUpdate(); 
                
                if (rowsAffected > 0) {
                    System.out.println("Data added successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to add data.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Failed!");
        }
    
    }//GEN-LAST:event_OkActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inActionPerformed


    public static void main(String[] args) {
         java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel EmpLabel;
    private javax.swing.JButton Ok;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField e;
    private javax.swing.JTextField in;
    private javax.swing.JTextField out;
    // End of variables declaration//GEN-END:variables
}
